version: "3.5"
services:
  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    volumes:
      - ./s3-data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
      MINIO_REGION: eu-west-1
    command: server /data --console-address ":9001"




